name: Build, Lint and Test
on: push
jobs:
    build:
        name: Build, Lint and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
            - run: cargo build --release --all-features
            - run: cargo test
            - run: cargo clippy
