name: coverage

on: [push]
jobs:
    test:
        name: coverage
        runs-on: ubuntu-latest
        container:
            image: xd009642/tarpaulin
            options: --security-opt seccomp=unconfined
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Generate code coverage
              run: cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml --coverall $COVERALLS_TOKEN
            - name: Upload to codecov.io
              uses: codecov/codecov-action@v1
              env:
                  super_secret: ${{ secrets.COVERALLS_TOKEN }}
              with:
                  fail_ci_if_error: false
